### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by afrabuck** [auto-chess-ui-mod/download#10]
Any chance for an update? Or has this project died? I've been enjoying it. Would be willing to donate a bit for the development.

**Comment by TiesdeKok** [comment]
The project has definitely not died, but life is a bit busy right now so I couldn't update it immediately. Fortunately there is already a fork by [`boingy`](https://github.com/auto-chess-ui-mod/source/pull/2) that should update everything for the May 25th update. I'll double check it and then I'll update the files.

**Comment by afrabuck** [comment]
That’s great news. Do you have anything set up to support development. It wouldn’t be a huge amount but I’d be willing to throw some support.

**Comment by TiesdeKok** [comment]
There is a "buy me some candy" button on the main page of the mod (https://github.com/auto-chess-ui-mod/download), but it is by no means necessary. :smile:
