### ISSUE TITLE
Stutter？

### ISSUE THREAD

**Issue by zizouqi** [auto-chess-ui-mod/download#5]
I find there will be stutter every second when I use this mod.

I haven't read your code, but I guess you are collecting data per second?

How about change it to per round? (Actually the DAC developers are deploying a new player info board, they collect data every round.)

**Comment by TiesdeKok** [comment]
Some other people have mentioned this as well, personally I don't notice anything but it could be my system is just beefier than the average system (or it could be coincidence).  

The data for the 5 drawn pieces is updated every second and the data for the list is updated once per round. 

You are right that I should probably calculate it once per round for the drawn pieces as well, initially I ran into some problems when doing this (i.e. it trying to calculate it before the draw board was completely loaded), but in the mean time I think I have figured out a solution to that problem. I'll post an update once I have optimized the code.

**Comment by TiesdeKok** [comment]
Update, for now I have modified the code so that it calculates it only when you draw new heroes. If I do it once per round it will not be up to date if you start re-rolling. Let me know if this solves the stutters! 

The newest version is live on Github.

**Comment by zizouqi** [comment]
Cool, I will try it later.

BTW, I posted your UI mod in the following three places:
- 小黑盒： https://www.xiaoheihe.cn/community/57743/list/22025714
- 旅法师营地： https://www.iyingdi.com/web/bbspost/detail/1900079
- My personal Weibo (Chinese version Twitter): https://weibo.com/ttarticle/p/show?id=2309404365097127543404
